### ISSUE TITLE
Pocketed Balls on Metal Table not positioned correctly if table is Toggled locally.

### ISSUE THREAD

**Issue by BluWizard10** [FairlySadPanda/vrcbce#106]
If the Metal Pool Table has a toggle and someone is playing it (but it's Toggled Off for you locally), the pocketed balls will not be positioned correctly once you toggle it on.

Not sure if this is a local issue or some kind of physics issue, but I wanted to point it out. See the screenshot I attached below of what it looks like when I toggled on an active pool game with pocketed balls.

![VRChat_3840x2160_2021-09-06_18-26-48 830](https://user-images.githubusercontent.com/17975114/132375795-0c52e548-6cff-4878-bbd6-9d189a92e3c6.png)

**Comment by Metamaniac** [comment]
This is specifically an issue with the fact that the transform for that table exists *solely* because of late-joiners and people with the table toggled off (then on) needing to see the state of the game up to that point; for people who play the game, Unity's physics system is purely used once a ball gets pocketed and whether they end up at the bottom or not is handled by that.

In this case, I think the real issue is actually that it's not positioned properly for the metal tables as-is, as this is something I overlooked when implementing it. (it should be where the lowest rack is)

Will be fixed, thanks for letting us know!

**Comment by Metamaniac** [comment]
As of commits https://github.com/FairlySadPanda/vrcbce/commit/d9b73934364afc5d353901e9ca96a020923d4c28, https://github.com/FairlySadPanda/vrcbce/commit/c79bc4cf801e5a4522c07c6fb1eb789fabb670fa, and https://github.com/FairlySadPanda/vrcbce/commit/1ae4a3ba76945da244d1541926c2e83a91bc2160, this issue should be fixed 👍
