### ISSUE TITLE
Add VRC Spatial Audio Source (Script) to CueHitSound

### ISSUE THREAD

**Issue by jamestruhlar** [FairlySadPanda/vrcbce#110]
![2021-09-15 23_00_33-VRC Worlds (Quest) - FiveSkies - Android - Unity 2019 4 29f1 Personal _DX11_](https://user-images.githubusercontent.com/8117029/133547400-89cd12d5-fb03-4195-b575-583bb7485815.png)

It always bugs me when these messages pop up in the sdk build tab. Probably a non-issue since it's just a warning, but I figured it never hurts to ask.

I usually add the script and uncheck Enable Spatialization so it doesn't affect the hit sound curves. Aside from just being slightly inconvenient, is there a reason to _not_ add the script there?

**Comment by Metamaniac** [comment]
VRC Spatial Audio Source sucks because it *does* effect the curves, no matter what your settings are. I had this issue in Truancy for ages where despite having the curves set up properly for 2D spatialization to turn 3D after a certain distance, it just wouldn't work with *any* settings combination, leading me to think it was actually a Unity issue for quite some time. Of course- the issue went away with nuking VRC Spatial Audio Source, and I realized it was also what was giving me trouble with all my other audio sources as well. The script is one big black box that's outside of anyone's control (but VRChat) and the only way to ensure that your audio source is 100% represented correctly the way you want it to is to leave it out. Hence why that warning is basically the only time I tell people the SDK is straight up ***wrong*** and they should ignore it.
