### ISSUE TITLE
Make the turn better visible.

### ISSUE THREAD

**Issue by MrDummyNL** [FairlySadPanda/vrcbce#33]
I noticed the cue colors are even bright even turns are changed. This will confuse some people.
I know you made "thing" sound but it will not help deaf and (hard) bad hearing, makes the game not very deaf-friendly.
Also in busy room, they might even miss sound. So we need good visuals for each turn.

I want tell Harry did good job with changing brightness level in cues in his builds, showing your turn (brighter color) and when it's over (much dimmer color).

Can you make it possible? Thanks!

Today a lot playing, looking at debug window, it says table color change should happens, but i dont see on table lights. Please verify why table lights are not working.

**Comment by MrDummyNL** [comment]
v1.1.1 fixed table lights so that is good.
Cue sticks still have same brightness. Not sure it's problem, it's small cosmetic side / indication help.

**Comment by FairlySadPanda** [comment]
Am working on this for 1.1.2 Sent from Mail for Windows 10 From: MrDummy_NLSent: 03 June 2021 00:30To: FairlySadPanda/vrcbceCc: SubscribedSubject: Re: [FairlySadPanda/vrcbce] Make the turn better visible. (#33) v1.1.1 fixed table lights so that is good.Cue sticks still have same brightness. Not sure it's problem, it's small cosmetic side / indication help.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by FairlySadPanda** [comment]
This should be fixed.
