### ISSUE TITLE
Explore integration with UdonChips.

### ISSUE THREAD

**Issue by FairlySadPanda** [FairlySadPanda/vrcbce#59]
UdonChips is the first portable money system for Udon that's gained attention. Review the prefab. Does it gel well with VRCBCE? If so, write an example integration of it where it costs n amount of money to play a game of pool.

**Comment by Legoman99573** [comment]
Maybe as an optional dependency, but I would need to know how it works and might use it. Do you have a link to udon chips so that I can take a look at it?

**Comment by FairlySadPanda** [comment]
The way to handle this is an UdonBehaviour that acts as a translator, and then we support the features we'd want from a generic money system as a pseudo-interface.

**Comment by esnya** [comment]
UdonChips makes the game world more complex and fun.

I've been working on some integration mechanisms for UdonChips. Right now I'm trying to integrate this billiard table. When it's done, I can make it PR.

The main consepts I'm thinking about are as follows.

1. Pay-per-play: all players will have to pay a small amount of money before they can participate.
2. Cash prizes: The winners will be paid cash prizes. I also plan to increase the prize money by betting more money before the game starts.

Another idea is a prize based on the player's score. However, this is going to be difficult because I don't know anything about 4-ball scores.

**Comment by Legoman99573** [comment]
I would make it a soft dependency as some worlds makers may not want to work with it.

**Comment by FairlySadPanda** [comment]
Resolved due to #74 being merged. Thanks @esnya!
