### ISSUE TITLE
Pool Table Doesn't Reset if players left.

### ISSUE THREAD

**Issue by NataIynn** [FairlySadPanda/vrcbce#63]
If players leave during a active game the pool table doesn't reset. I've tried clicking reset/end button but it doesn't work and users aren't in the world.
![image](https://user-images.githubusercontent.com/28743579/123335981-daab9800-d50a-11eb-9908-4b425b1fcd50.png)

**Comment by Legoman99573** [comment]
Could add options to allow world masters and/or instance creators to instantly reset the table regardless if they are in a game or not.

**Comment by FairlySadPanda** [comment]
Have fixed a clanger of a bug here with 1.1.5 which should greatly help with this problem.

**Comment by NataIynn** [comment]
Tested, seems still to happen. 
![image](https://user-images.githubusercontent.com/28743579/123728028-3ef69080-d858-11eb-9a3b-b0c1f7287796.png)

![image](https://user-images.githubusercontent.com/28743579/123728040-44ec7180-d858-11eb-9140-2b1976e86c79.png)
Also pool cues don't reset correctly.

**Comment by FairlySadPanda** [comment]
Strange. I will take a look later today.

**Comment by NataIynn** [comment]
Actually It's happening way more frequent now.

**Comment by FairlySadPanda** [comment]
Have taken a quick look. 

I've changed the OnPlayerLeft code in PoolStateManager.cs to this:

```        public override void OnPlayerLeft(VRCPlayerApi player)
        {
            if (!Networking.IsOwner(Networking.LocalPlayer, gameObject) || !Utilities.IsValid(player))
            {
                return;
            }

            int playerID = player.playerId;
            if (playerID == player1ID || playerID == player2ID || playerID == player3ID || playerID == player4ID)
            {
                if (isGameInMenus)
                {
                    RemovePlayerFromGame(playerID);
                }
                else
                {
                    gameWasReset = true;
                    ForceReset();
                }
            }
        }```

The code is now in master in the latest commit here. 

I'll improve the ForceReset code so it pops up a window asking for confirmation before resetting in 1.2.0.

The cue glitch could be an issue with your local install of VRCBCE running into oddities due to the changes made between 1.1.0 and now. If possible, try wiping the VRCBCE prefab entirely from your install and installing latest.

I've updated the 1.1.5 release package with this hotfix. Hopefully it helps.

**Comment by NataIynn** [comment]
I'm testing it currently, I'll let you know. I've replaced all VRC Pool Table prefabs, so they're fully updated with 1.1.6.,

**Comment by NataIynn** [comment]
Went into existing instanced and it was broken. Locked and cant reset. You can check at A Quiet Loft. 
![VRChat_1920x1080_2021-07-02_05-42-45 040](https://user-images.githubusercontent.com/28743579/124263331-bc403080-daf8-11eb-965b-282bfdddf914.png)
![VRChat_1920x1080_2021-07-02_05-42-47 314](https://user-images.githubusercontent.com/28743579/124263336-bea28a80-daf8-11eb-9ea8-255e8742553a.png)

**Comment by FairlySadPanda** [comment]
I've gone in and rewritten the reset code, but have not tested it yet due to work commitments.

https://github.com/FairlySadPanda/vrcbce/releases/tag/1.1.7

As said in the ticket this should make it more stable when resetting when a player leaves the world, and if the pool is in a bad state - someone's left and the table hasn't reset - (and nothing has crashed) anyone can reset the game.

**Comment by NataIynn** [comment]
tested and works good now. I havent seen a broken pool table yet. Other than floating cues.
