### ISSUE TITLE
Player color no longer updating on table

### ISSUE THREAD

**Issue by jamestruhlar** [FairlySadPanda/vrcbce#86]
I'm going slightly bonkers trying to figure out why the _EmissionColor isn't updating on the pool table since updating to unity 2019 and working with a fresh install of VRCBCE 1.3.0. There are no errors in the console and I've tested in game and via cyanemu.

It used to work -- so I figure I must have broken something in the process of upgrading things. Hopefully someone here can help me figure it out.

![2021-08-11 16_42_11-Window](https://user-images.githubusercontent.com/8117029/129107422-d4643de7-f183-4589-b4ec-4086c8592542.png)

**Comment by Metamaniac** [comment]
I addressed this in https://github.com/FairlySadPanda/vrcbce/issues/85

This was fixed in https://github.com/FairlySadPanda/vrcbce/commit/98619d4d9bb0cc8e2e029cedecaf2a39d2bc92f0 but there hasn't been an official release yet. For now you can download the repo directly and replace the one in your unity project or wait for the official unitypackage (I'll bug Panda for a release ASAP)
