### ISSUE TITLE
type name space "is valid" is missing in Utilities

### ISSUE THREAD

**Issue by Timothy3dfbc** [FairlySadPanda/vrcbce#96]
I must be overlooking something but have all  requerments in world yet I get the follwing red messages? any ideas are welcome

![image](https://user-images.githubusercontent.com/58902355/131387858-179a3524-99a7-4c85-9c9c-d6b765e1d42b.png)

**Comment by Metamaniac** [comment]
Could it be the same as https://github.com/FairlySadPanda/vrcbce/issues/93#issuecomment-904267980 ?

**Comment by Hexlight-was-taken** [comment]
Also currently having this issue but i can't see how that answer solves it. Amore detailed explanation would be good on what to change and where.

**Comment by Metamaniac** [comment]
@Hexlight-was-taken Try importing the latest SDK, UdonSharp 0.20.2 or later, then reimport the project (either by deleting both the FSP and VRCBilliards folders before reimporting the unitypackage, or right clicking both folders and hitting "reimport")

**Comment by Metamaniac** [comment]
@Timothy3dfbc @Hexlight-was-taken As of commit https://github.com/FairlySadPanda/vrcbce/commit/bb22090affbb68ea92603f78d6f130bffe65ef24, the chance of U# getting confused and causing this should be properly mitigated; will be fixed in next release! (which will be soon) (you can also download the repo directly if you want it early)
